### ISSUE TITLE
Add usage of convert_xml2txt in gen_usms_xml2txt

### ISSUE THREAD

**Issue by plecharpent** [SticsRPacks/SticsRFiles#17]
- [x]  keep compatibility with actual behaviour using JavaStics cmd line for converting xml files to text files
- [x]  use the right function for getting files list for each usm (fix issue #16 before): get_usms_files
- [x]  add an option in args for selecting either javastics cmd use or convert_xml2txt conversion
- [x]  use of convert_xml2txt
    - [x]  add missing files to be converted param.sol (#14), param_gen and param_newform
    - [x]  add gen_new_travail call
    - [x]  add gen_climate call (to be implemented #15)
    - [x]  add files copy for var.mod, prof.mod, rap.mod (from config of javastics or from the workspace)
